### PR TITLE
Solve issue 153

### PR DESCRIPTION
**Pull request by ch222kv**
Solves #153 by setting the color to transparent if you click on the counter div.

### CODE REVIEW

**Comment by davidsoderberg** [comment]
How are the user supposed to get it back?

**Comment by ch222kv** [comment]
If you press the same area again you get the counter back. This is of course not that intuitive, but we could add a border or something to display that there is something there?

**Comment by davidsoderberg** [comment]
Or an icon.

**Comment by ch222kv** [comment]
Now there is a light border around it. But Jorryt didn't seem that keen on having it there at all, was it because it was distraction or some other reason?

**Comment by aseea** [comment]
Without saying too much i think its a part of the learning process. Knowing how many cubes you've placed and how many cubes it takes to fill the whole area. And maybe thats why she wants it to be optional?

**Comment by davidsoderberg** [comment]
That is possible :smile:

**Comment by ch222kv** [comment]
Since she doesn't provide any reason for her opinion it's quite hard to actually solve it then. As it is right now it is possible to hide it and there is a very light border around the area where you have to click to enable it again, minimal clutter, but does that conform to her expectations?

**Comment by davidsoderberg** [comment]
We do not know that and can not ask here... She is back att friday afternoon.

**Comment by mn22nw** [comment]
I have another idea for this solution.
The basic idea is to have an arrow that hides the div to the right outside of the screen (maybe with a little transition to make it look nicer)
> Antal kuber 0  

And when the counter div is hidden <  (arrow to show it again)  is the only thing that's visible on the screen.

**Comment by davidsoderberg** [comment]
Sounds good :smile:

**Comment by aseea** [comment]
That way you would hide the p-element with the actual counter in it.

**Pull request closed without merging**
